apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://argoproj.github.io/argo-helm'
    chart: argo-workflows
    targetRevision: 2.0.3
    helm:
      values: |
        workflow:
          serviceAccount:
            create: true
        server:
          extraArgs:
            - --auth-mode=server
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - argo.localhost
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true