apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: universal-vercel-like-builder
spec:
  entrypoint: build-pipeline
  arguments:
    parameters:
      - name: repo_url
      - name: commit_sha
      - name: app_name

  volumeClaimTemplates:
    - metadata:
        name: workspace
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi

  templates:
    - name: build-pipeline
      steps:
        - - name: clone
            template: git-clone
        - - name: build
            template: railpack-build

    - name: git-clone
      script:
        image: alpine/git:latest
        workingDir: /workspace
        command: [sh, -ebc]
        script: |
          git clone {{workflow.parameters.repo_url}} .
          git checkout {{workflow.parameters.commit_sha}}
        volumeMounts:
          - name: workspace
            mountPath: /workspace

    # ШАГ СБОРКИ ЧЕРЕЗ RAILPACK
    - name: railpack-build
      container:
        # Используем официальный образ с Railpack & BuildKit
        image: ghcr.io/railwayapp/railpack:latest
        securityContext:
          privileged: true # Требуется для монтирования файловой системы BuildKit
        workingDir: /workspace
        command: ["/bin/sh", "-c"]
        args:
          - |
            # 1. Запускаем локальный BuildKit daemon в фоновом режиме
            buildkitd --addr tcp://127.0.0.1:1234 &
            
            # Ждем готовности socket
            sleep 3
            
            # 2. Собираем и сразу отправляем образ в наш локальный k3d registry
            railpack build \
              --buildkit-addr tcp://127.0.0.1:1234 \
              --tag k3d-registry.localhost:5000/{{workflow.parameters.app_name}}:{{workflow.parameters.commit_sha}} \
              --publish \
              .
        volumeMounts:
          - name: workspace
            mountPath: /workspace