apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: universal-vercel-like-builder
spec:
  entrypoint: build-pipeline
  arguments:
    parameters:
      - name: repo_url
      - name: commit_sha
      - name: app_name
  volumeClaimTemplates:
    - metadata:
        name: workspace
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
  templates:
    - name: build-pipeline
      steps:
        - - name: clone
            template: git-clone
        - - name: build
            template: buildpacks-build

    - name: git-clone
      container:
        image: alpine/git:v2.36.3
        command: [sh, -c]
        args:
          - git clone {{workflow.parameters.repo_url}} /workspace && cd /workspace && git checkout {{workflow.parameters.commit_sha}} || true
        volumeMounts:
          - name: workspace
            mountPath: /workspace

    - name: buildpacks-build
      container:
        # Вместо pack используем сам образ строителя
        image: paketobuildpacks/builder-jammy-base:latest
        
        # Важно: запускаем от имени root, чтобы получить доступ к исходникам, скачанным шагом git-clone
        securityContext:
          runAsUser: 0
        workingDir: /workspace
        
        # Запускаем нативный оркестратор Buildpacks (без Docker-демона)
        command: ["/cnb/lifecycle/creator"]
        args:
          - "-app=/workspace"
          - "-cache-dir=/workspace/cache"
          # Имя образа, который мы хотим собрать и отправить
          - "k3d-registry.localhost:5000/{{workflow.parameters.app_name}}:{{workflow.parameters.commit_sha}}"
        env:
          # Разрешаем пушить в наш локальный http-реестр
          - name: CNB_INSECURE_REGISTRIES
            value: "k3d-registry.localhost:5000"
        volumeMounts:
          - name: workspace
            mountPath: /workspace