apiVersion: argoproj.io/v1alpha1
kind: WorkflowEventBinding
metadata:
  name: deck-web-mr
  namespace: argo
spec:
  event:
    selector: >
      discriminator == "deck-web-mr" &&
      payload.object_kind == "merge_request" &&
      payload.object_attributes.action in ["open", "reopen", "update"]
  submit:
    workflowTemplateRef:
      name: universal-vercel-like-builder
      clusterScope: true
    arguments:
      parameters:
        - name: repo_url
          valueFrom:
            event: payload.project.git_http_url
        - name: commit_sha
          valueFrom:
            event: payload.object_attributes.last_commit.id
        - name: app_name
          valueFrom:
            event: payload.project.path_with_namespace
        - name: project_id
          valueFrom:
            event: payload.project.id
        - name: event_kind
          valueFrom:
            event: payload.object_kind
