apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-webhook
  namespace: argo
secrets:
  - name: gitlab-webhook-token
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-webhook-token
  namespace: argo
  annotations:
    kubernetes.io/service-account.name: gitlab-webhook
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitlab-webhook-submitter
  namespace: argo
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflows", "workfloweventbindings", "workflowtemplates"]
    verbs: ["create", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-webhook-submitter
  namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitlab-webhook-submitter
subjects:
  - kind: ServiceAccount
    name: gitlab-webhook
    namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab-webhook-cluster-template
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-workflows-server-cluster-template
subjects:
  - kind: ServiceAccount
    name: gitlab-webhook
    namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-server-webhook-reader
  namespace: argo
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-server-webhook-reader
  namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-server-webhook-reader
subjects:
  - kind: ServiceAccount
    name: argo-workflows-server
    namespace: argo
